const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '../promptpilot/static/index.html'), 'utf8');
for (const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)) new vm.Script(m[1]);
const context = vm.createContext({esc: value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')});
vm.runInContext(html.slice(html.indexOf('function workflowCandidateHtml('), html.indexOf('function renderWorkflowDetail(')), context);
assert.match(context.workflowCandidateHtml(null, [], []), /ещё не передана/);
const candidate = {candidate_id:'new', candidate_revision:'a'.repeat(40), repository_path:'C:/<script>bad</script>'};
const oldPass = {event_type:'candidate.gate_finished', payload:{candidate_id:'old', verdict:'PASS'}};
let rendered = context.workflowCandidateHtml(candidate, [oldPass], [{role:'reviewer', input:{candidate_id:'old'}, output:{result:'AUDIT_VERDICT: PASS'}}]);
assert.doesNotMatch(rendered, /PASS/);
assert.doesNotMatch(rendered, /<script>/);
assert.match(rendered, /&lt;script&gt;/);
rendered = context.workflowCandidateHtml(candidate, [oldPass, {event_type:'candidate.invalidated', payload:{candidate_id:'new'}}], []);
assert.match(rendered, /сдача аннулирована/);
assert.match(rendered, /a{40}/);
console.log('Candidate UI: current handoff evidence, invalidation, full details and escaping OK');
